<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1707832996814' stop='1707832999192'>
    <name>test/UAT_Cognito/AuthService_Delete_User.test.js</name>
    <title>test/UAT_Cognito/AuthService_Delete_User.test.js</title>
    <test-cases>
        <test-case start='1707832996814' status='failed' stop='1707832997957'>
            <name>API Success</name>
            <title>API Success</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1707832996816' status='undefined'>
                    <name>Values passed:""</name>
                    <title>Values passed:""</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:25:13)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1707832997957' status='failed' stop='1707832998565'>
            <name>Email already exist</name>
            <title>Email already exist</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1707832997958' status='undefined'>
                    <name>Values passed:""</name>
                    <title>Values passed:""</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:46:13)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1707832998565' status='failed' stop='1707832999183'>
            <name>BAD Request</name>
            <title>BAD Request</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1707832998566' status='undefined'>
                    <name>Values passed:""</name>
                    <title>Values passed:""</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "argument of type 'NoneType' is not iterable"
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "argument of type 'NoneType' is not iterable"
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:68:13)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>